version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

env:
  parameter-store:
    REACT_APP_SPACE_ID: "contentful_space_id_parameter"
    REACT_APP_ACCESS_TOKEN: "contentful_access_token"

  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - REACT_APP_BUILD_NUMBER=$CODEBUILD_BUILD_NUMBER yarn build

artifacts:
  files:
    - "**/*"
  name: "jonnypillar_ui_build_artifact"
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'